<?php

namespace App\Models;

use Illuminate\Support\Facades\Log;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Jadwal extends Model
{
    use HasFactory;
    protected $table = 'jadwal';
    protected $primaryKey = null;
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false;
    protected $fillable = [
        'id_mengajar',
        'waktu',
        'hari',
        'kelas_id'
    ];
    protected $hidden;

    public $data_kelas = [
        '7' => ['7W','7R','7Y'],
        '8' => ['8W','8R',],
        '9' => ['9W','9R','9Y',],
        '10' => ['10W','10R',],
        '11' => ['11W','11R',],
        '12' => ['12'],
    ];

    public $data_mengajar = [
        [
            "id" => 0,
            "mata_pelajaran_ref" => "56d09ba4-5670-4473-99b8-752cb941b75d",
            "nama_mata_pelajaran" => "Katrina",
            "jumlah_jam" => 8, //perminggu (rev)
            "max_jam" => 2, // max_perhari (rev)
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Morgan",
        ],
        [
            "id" => 1,
            "mata_pelajaran_ref" => "6e366b9c-e6fe-4da9-99a7-cdafd1e07625",
            "nama_mata_pelajaran" => "West",
            "jumlah_jam" => 5,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Kimberly",
        ],
        [
            "id" => 2,
            "mata_pelajaran_ref" => "eddc0763-c0fb-441a-9861-00ee66116f56",
            "nama_mata_pelajaran" => "Jannie",
            "jumlah_jam" => 6,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Odonnell",
        ],
        [
            "id" => 3,
            "mata_pelajaran_ref" => "24d1865d-1523-4810-871b-ee8048d0b952",
            "nama_mata_pelajaran" => "Dale",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Carmella",
        ],
        [
            "id" => 4,
            "mata_pelajaran_ref" => "4de8ff3a-3f9f-4742-b575-f31eeaf10a79",
            "nama_mata_pelajaran" => "Katharine",
            "jumlah_jam" => 4,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Hatfield",
        ],
        [
            "id" => 5,
            "mata_pelajaran_ref" => "914b317a-fc52-4936-a74b-7006c6723013",
            "nama_mata_pelajaran" => "Davidson",
            "jumlah_jam" => 5,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Hutchinson",
        ],
        [
            "id" => 6,
            "mata_pelajaran_ref" => "726ca446-f163-4a8e-8f56-eb506e63b183",
            "nama_mata_pelajaran" => "Sims",
            "jumlah_jam" => 5,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Janet",
        ],
        [
            "id" => 7,
            "mata_pelajaran_ref" => "59afc92f-21cf-4880-9ee6-8f8002dab6b4",
            "nama_mata_pelajaran" => "Susanne",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Michelle",
        ],
        [
            "id" => 8,
            "mata_pelajaran_ref" => "6eb20e76-e42f-4404-9dd6-94b33f9759b7",
            "nama_mata_pelajaran" => "Latisha",
            "jumlah_jam" => 5,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 12,
            "nama_guru" => "Kathleen",
        ],
        [
            "id" => 9,
            "mata_pelajaran_ref" => "11ae6a0b-5d15-40bb-bfd7-49c4748b5246",
            "nama_mata_pelajaran" => "Kerry",
            "jumlah_jam" => 5,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Merle",
        ],
        [
            "id" => 10,
            "mata_pelajaran_ref" => "15e57448-b922-4044-a9dd-19e82f6d7552",
            "nama_mata_pelajaran" => "Hayes",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Jacklyn",
        ],
        [
            "id" => 11,
            "mata_pelajaran_ref" => "f4d2808c-29ec-425a-aa27-cf6f2a73a233",
            "nama_mata_pelajaran" => "Pena",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 12,
            "nama_guru" => "Villarreal",
        ],
        [
            "id" => 12,
            "mata_pelajaran_ref" => "187dbfd2-9248-4243-a606-8e94aff2b095",
            "nama_mata_pelajaran" => "Mckinney",
            "jumlah_jam" => 4,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Pitts",
        ],
        [
            "id" => 13,
            "mata_pelajaran_ref" => "3b420740-8c68-4660-aae2-ef3ec7746bac",
            "nama_mata_pelajaran" => "Gibbs",
            "jumlah_jam" => 4,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Lola",
        ],
        [
            "id" => 14,
            "mata_pelajaran_ref" => "ddadfd86-6aa2-4c5f-857f-a28aec34130d",
            "nama_mata_pelajaran" => "Lloyd",
            "jumlah_jam" => 5,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Jane",
        ],
        [
            "id" => 15,
            "mata_pelajaran_ref" => "0cdad1de-ead8-4d07-a977-f314640dac24",
            "nama_mata_pelajaran" => "Terry",
            "jumlah_jam" => 4,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Emily",
        ],
        [
            "id" => 16,
            "mata_pelajaran_ref" => "12e0ee2a-af9d-4b19-88bf-531e064325c3",
            "nama_mata_pelajaran" => "Krystal",
            "jumlah_jam" => 6,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 12,
            "nama_guru" => "Daniel",
        ],
        [
            "id" => 17,
            "mata_pelajaran_ref" => "9e77ab99-ad36-4352-adb8-36583b673483",
            "nama_mata_pelajaran" => "Terrell",
            "jumlah_jam" => 5,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Madelyn",
        ],
        [
            "id" => 18,
            "mata_pelajaran_ref" => "8b4efa09-7dda-4451-a1f0-042d8e933ac7",
            "nama_mata_pelajaran" => "Hancock",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Fuentes",
        ],
        [
            "id" => 19,
            "mata_pelajaran_ref" => "128c4cf7-916f-43ac-b994-159f3dfc904a",
            "nama_mata_pelajaran" => "Higgins",
            "jumlah_jam" => 7,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Violet",
        ],
        [
            "id" => 20,
            "mata_pelajaran_ref" => "11eaecff-b97d-4d62-afbd-d1b2c522303b",
            "nama_mata_pelajaran" => "Ericka",
            "jumlah_jam" => 4,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Fletcher",
        ],
        [
            "id" => 21,
            "mata_pelajaran_ref" => "96d1d852-62aa-4a37-85ce-f9438f33dbe4",
            "nama_mata_pelajaran" => "Larsen",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Abbott",
        ],
        [
            "id" => 22,
            "mata_pelajaran_ref" => "561f02c7-cc61-4dea-ba45-14f83b4ba538",
            "nama_mata_pelajaran" => "Vance",
            "jumlah_jam" => 4,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Sharp",
        ],
        [
            "id" => 23,
            "mata_pelajaran_ref" => "35e92b03-fc01-4b4b-9da3-b66dc6f23cc3",
            "nama_mata_pelajaran" => "Tasha",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Susie",
        ],
        [
            "id" => 24,
            "mata_pelajaran_ref" => "34866917-e49b-43df-86fa-56d5465a1027",
            "nama_mata_pelajaran" => "Sherry",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Molly",
        ],
        [
            "id" => 25,
            "mata_pelajaran_ref" => "16997550-085a-4692-85db-c7c93550d84d",
            "nama_mata_pelajaran" => "Terry",
            "jumlah_jam" => 8,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Essie",
        ],
        [
            "id" => 26,
            "mata_pelajaran_ref" => "6343062b-f33a-4cf4-a644-fb3ca2210951",
            "nama_mata_pelajaran" => "Blackburn",
            "jumlah_jam" => 8,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Cherie",
        ],
        [
            "id" => 27,
            "mata_pelajaran_ref" => "8233eda2-f26a-46d3-aba4-a58398932c17",
            "nama_mata_pelajaran" => "Kerri",
            "jumlah_jam" => 7,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Zamora",
        ],
        [
            "id" => 28,
            "mata_pelajaran_ref" => "8d08dd58-28d5-4ebf-9eaf-96560df07b7f",
            "nama_mata_pelajaran" => "Therese",
            "jumlah_jam" => 8,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Clay",
        ],
        [
            "id" => 29,
            "mata_pelajaran_ref" => "f32acbb6-e1b9-45a8-b532-25f902d5b34b",
            "nama_mata_pelajaran" => "Kathy",
            "jumlah_jam" => 6,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Lynne",
        ],
        [
            "id" => 30,
            "mata_pelajaran_ref" => "0334e053-ad58-480d-87a8-d4b7f2bc612e",
            "nama_mata_pelajaran" => "Norton",
            "jumlah_jam" => 7,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Marva",
        ],
        [
            "id" => 31,
            "mata_pelajaran_ref" => "8d7dee33-788e-40d6-9814-2d2778910069",
            "nama_mata_pelajaran" => "Lena",
            "jumlah_jam" => 8,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 12,
            "nama_guru" => "Castro",
        ],
        [
            "id" => 32,
            "mata_pelajaran_ref" => "d48c4587-48a6-4129-b44d-451a67f3a76b",
            "nama_mata_pelajaran" => "Penelope",
            "jumlah_jam" => 7,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Bean",
        ],
        [
            "id" => 33,
            "mata_pelajaran_ref" => "60c32104-6387-433d-aefd-f4aea325df0f",
            "nama_mata_pelajaran" => "Sheena",
            "jumlah_jam" => 4,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Pratt",
        ],
        [
            "id" => 34,
            "mata_pelajaran_ref" => "19c6783b-c775-4533-9946-45a804d074cb",
            "nama_mata_pelajaran" => "Tommie",
            "jumlah_jam" => 8,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Christina",
        ],
        [
            "id" => 35,
            "mata_pelajaran_ref" => "eca1de02-7635-4d5e-a8c9-949293eea73c",
            "nama_mata_pelajaran" => "Duncan",
            "jumlah_jam" => 8,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Lori",
        ],
        [
            "id" => 36,
            "mata_pelajaran_ref" => "b4067012-54bd-41b5-9b4e-bba15d779301",
            "nama_mata_pelajaran" => "Adele",
            "jumlah_jam" => 4,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Dalton",
        ],
        [
            "id" => 37,
            "mata_pelajaran_ref" => "f5cbb02f-5217-4b12-bdb7-a9e53e5d9588",
            "nama_mata_pelajaran" => "Moody",
            "jumlah_jam" => 5,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 11,
            "nama_guru" => "Nannie",
        ],
        [
            "id" => 38,
            "mata_pelajaran_ref" => "b5bdf817-0afa-4cd0-8a23-71e0e1e06a2f",
            "nama_mata_pelajaran" => "Burton",
            "jumlah_jam" => 6,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Moses",
        ],
        [
            "id" => 39,
            "mata_pelajaran_ref" => "ab7a5390-b180-45fd-a200-a76c3599c47f",
            "nama_mata_pelajaran" => "Lorene",
            "jumlah_jam" => 7,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Hart",
        ],
        [
            "id" => 40,
            "mata_pelajaran_ref" => "cd7a7d27-24eb-4f2a-b7eb-958ffb2521fe",
            "nama_mata_pelajaran" => "Jaclyn",
            "jumlah_jam" => 6,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Marguerite",
        ],
        [
            "id" => 41,
            "mata_pelajaran_ref" => "42866a24-f8e5-4b37-9ec0-e06a905cc430",
            "nama_mata_pelajaran" => "Rhonda",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 12,
            "nama_guru" => "Patrica",
        ],
        [
            "id" => 42,
            "mata_pelajaran_ref" => "24e65b02-81b2-4841-8d5a-b05b9c5452b8",
            "nama_mata_pelajaran" => "Bianca",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Frederick",
        ],
        [
            "id" => 43,
            "mata_pelajaran_ref" => "2fdee29d-2302-4a62-8d79-6aa8b3e51f9d",
            "nama_mata_pelajaran" => "Bernadine",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Kim",
        ],
        [
            "id" => 44,
            "mata_pelajaran_ref" => "470494ed-d352-4dd7-b0aa-3f3244c9f072",
            "nama_mata_pelajaran" => "Hyde",
            "jumlah_jam" => 4,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Ronda",
        ],
        [
            "id" => 45,
            "mata_pelajaran_ref" => "8e0815f6-3799-4f60-a220-de745f6a5b2e",
            "nama_mata_pelajaran" => "Reynolds",
            "jumlah_jam" => 8,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Roach",
        ],
        [
            "id" => 46,
            "mata_pelajaran_ref" => "9224d34f-f7c4-49c7-ac31-a87b47e9b90a",
            "nama_mata_pelajaran" => "Amalia",
            "jumlah_jam" => 6,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Baxter",
        ],
        [
            "id" => 47,
            "mata_pelajaran_ref" => "6cd99111-77b0-449e-9dc8-56c784e09f0e",
            "nama_mata_pelajaran" => "Donaldson",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 12,
            "nama_guru" => "Lana",
        ],
        [
            "id" => 48,
            "mata_pelajaran_ref" => "a04808fe-1461-418f-a46b-998d093dad9d",
            "nama_mata_pelajaran" => "Mckenzie",
            "jumlah_jam" => 4,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 10,
            "nama_guru" => "Natasha",
        ],
        [
            "id" => 49,
            "mata_pelajaran_ref" => "87090638-cc55-46dc-8f0b-ea5079a5c5c2",
            "nama_mata_pelajaran" => "Fern",
            "jumlah_jam" => 8,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Frost",
        ],
        [
            "id" => 50,
            "mata_pelajaran_ref" => "f77af056-fbbc-4327-9c9a-7a26cfd64751",
            "nama_mata_pelajaran" => "Belinda",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Chang",
        ],
        [
            "id" => 51,
            "mata_pelajaran_ref" => "8508b2dd-b984-4e66-9fd5-47b303acfdce",
            "nama_mata_pelajaran" => "Britt",
            "jumlah_jam" => 7,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Hoover",
        ],
        [
            "id" => 52,
            "mata_pelajaran_ref" => "3f19e277-c4c9-4ddb-9070-a9ce06052a3d",
            "nama_mata_pelajaran" => "Morin",
            "jumlah_jam" => 8,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Kirkland",
        ],
        [
            "id" => 53,
            "mata_pelajaran_ref" => "e32e069e-e2a3-404f-b7f6-9f7b126765aa",
            "nama_mata_pelajaran" => "Dickson",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Celia",
        ],
        [
            "id" => 54,
            "mata_pelajaran_ref" => "70ae2d06-e447-4762-8333-f989a130e501",
            "nama_mata_pelajaran" => "Reyes",
            "jumlah_jam" => 6,
            "max_jam" => 1,
            "semester" => 1,
            "jenjang" => 8,
            "nama_guru" => "Baldwin",
        ],
        [
            "id" => 55,
            "mata_pelajaran_ref" => "2f0447da-7897-42fa-b9e3-d0c513ce727c",
            "nama_mata_pelajaran" => "Marjorie",
            "jumlah_jam" => 6,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 7,
            "nama_guru" => "Miranda",
        ],
        [
            "id" => 56,
            "mata_pelajaran_ref" => "346b6564-fda7-4158-9936-9a81d34be637",
            "nama_mata_pelajaran" => "Nita",
            "jumlah_jam" => 5,
            "max_jam" => 2,
            "semester" => 1,
            "jenjang" => 9,
            "nama_guru" => "Phelps",
        ],
    ];

    public $data_jam = [
        ['MP', '7:20','7:30'],
        ['1', '7:30','8:10'],
        ['2', '8:10','8:50'],
        ['3', '8:50','9:30'],
        ['4', '9:30','10:10'],
        ['RECESS', '10:10','10:25'],
        ['5', '10:25','11:05'],
        ['6', '11:05','11:45'],
        ['7', '11:45','12:25'],
        ['LUNCH', '12:25','12:55'],
        ['8', '12:55','13:35'],
        ['9', '13:35','14:15'],
        ['10', '14:15','14:55'],
        ['HR', '14:55','15:00'],
    ];
    
    //$rangeArray inputan data mengejar yang sudah di kelompokan berdasarkan jenjang
    //$checkArray inputan dari jadwal yang nanti nya akan menjadi jadwal per hari
    //$currentPosition inputan dari looping untuk melihat sudah sejauh mana posisi secara horizontal
    // yang nantinya dipakai untuk melihat posisi secara vertikal juga
    static function getRandomId($rangeArray, $checkArray, $currenPosition) {
        //inisiasi array untuk menampung array apa saja yang sudah dicek memiliki kesamaan
        $verticalNumbers = [];
        $horizontalNumbers = $checkArray[$currenPosition];

        $position = count($horizontalNumbers) ; // mendapatkan posisi terakhir untuk penambahan terbaru
        //menambahkan angka dari posisi horizonal ke atas atau vertikal
        for ($i = 0; $i < count($checkArray); $i++) { 
            if (isset($checkArray[$i][$position])) {
                $verticalNumbers[] = $checkArray[$i][$position];
            } else {
                continue;
            }
        }
        $verticalNumbers = array_values(array_diff($verticalNumbers, ['BELAJAR', 'MP', 'RECESS', 'LUNCH', 'HR']));
        $horizontalNumbers = array_values(array_diff($horizontalNumbers, ['BELAJAR', 'MP', 'RECESS', 'LUNCH', 'HR']));
        //mencari angka yang sudah ada secara vertikal, jadi angka yang sama akan dibuang dan yang sama akan di masukan
        $availableNumbersVertical = array_values(array_intersect($rangeArray, $verticalNumbers));
        //mencari angka yang sama secara horizontal, jadi angka yang sama akan dibuang dan yang sama akan di masukan
        $availableNumbersHorinzontal = array_values(array_intersect($rangeArray, $horizontalNumbers));
        //mencari angka yang beda sebagai acuan angka apa saja yang belum ada terpakai
        $mergeArr = array_values(array_unique(array_merge($availableNumbersVertical, $availableNumbersHorinzontal)));
        $availableNumbersFixed = array_values(array_diff($rangeArray, $mergeArr));
        //jika tidak ada maka akan dikembalikan false
        if (empty($availableNumbersFixed)) {
            return false;
        }
        //melakukan interasi sampai mendapatkan angka yang belum ada dalam array
        $randomKey = array_rand($availableNumbersFixed);
        $randomNumber = $availableNumbersFixed[$randomKey];
        return $randomNumber;
    }
}
