<?php

namespace App\Models;

use Illuminate\Support\Facades\Log;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Nette\Utils\Arrays;

class Jadwal extends Model
{
    use HasFactory;
    protected $table = 'jadwal';
    protected $primaryKey = null;
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false;
    protected $fillable = [
        'id_mengajar',
        'waktu',
        'hari',
        'kelas_id'
    ];
    protected $hidden;

    public $data_kelas = [
        '7' => ['7W','7R','7Y'],
        '8' => ['8W','8R',],
        '9' => ['9W','9R','9Y',],
        '10' => ['10W','10R',],
        '11' => ['11W','11R',],
        '12' => ['12W'],
    ];
    
    //jika ada data yang sulit untuk di join gunakan mapping saja
    //tambahan data preferredDay, preferredTime yang nanti di tambahkan pada table ...
    //ekspetasi preferredDay dan preferredTime adalah 0,1,2,3,4...
    public $data_mengajar = [
        [
            "id" => "1",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP011",
            "nama_mata_pelajara" => "PKn",
            "jumlah_jam" => 7,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Achmad Jayadi",
            "kelas" => ["11R", "8R", "9R"],
        ],
        [
            "id" => "2",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "PrBL",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Achmad Jayadi",
            "kelas" => ["9R", "10R", "9Y"],
        ],
        [
            "id" => "3",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "PrBL",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Adhi Ginanjar Santoso",
            "kelas" => ["7Y", "8W", "8R"],
        ],
        [
            "id" => "4",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP025",
            "nama_mata_pelajara" => "Entre",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Adhi Ginanjar Santoso",
            "kelas" => ["11R", "11W", "9R"],
        ],
        [
            "id" => "5",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP030",
            "nama_mata_pelajara" => "CS",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Adhi Ginanjar Santoso",
            "kelas" => ["11W", "11W", "9W"],
        ],
        [
            "id" => "6",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP011",
            "nama_mata_pelajara" => "Mandarin",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Adjeng Florianti",
            "kelas" => ["7Y", "11R", "9R"],
        ],
        [
            "id" => "7",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP004",
            "nama_mata_pelajara" => "Math",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Ahmad Rizal",
            "kelas" => ["12W", "12W", "7Y"],
        ],
        [
            "id" => "8",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP023",
            "nama_mata_pelajara" => "Mat IPA/IPS",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Ahmad Rizal",
            "kelas" => ["8W", "11R", "7W"],
        ],
        [
            "id" => "9",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP012",
            "nama_mata_pelajara" => "PKn",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Andromeda Nova Abadi",
            "kelas" => ["11W", "7R", "9W"],
        ],
        [
            "id" => "10",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP005",
            "nama_mata_pelajara" => "Math",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Anggya Avosma",
            "kelas" => ["12W", "11W", "10R"],
        ],
        [
            "id" => "11",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP024",
            "nama_mata_pelajara" => "Mat IPA/IPS",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Anggya Avosma",
            "kelas" => ["10R", "9W", "11W"],
        ],
        [
            "id" => "12",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP003",
            "nama_mata_pelajara" => "English",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Anna Desiyanti",
            "kelas" => ["10R", "10W", "7W"],
        ],
        [
            "id" => "13",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP004",
            "nama_mata_pelajara" => "Literature",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Anna Desiyanti",
            "kelas" => ["9W", "10W", "9W"],
        ],
        [
            "id" => "14",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP005",
            "nama_mata_pelajara" => "Math",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Aprilia Loisita",
            "kelas" => ["9Y", "11R", "12W"],
        ],
        [
            "id" => "15",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP025",
            "nama_mata_pelajara" => "Mat IPA/IPS",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Aprilia Loisita",
            "kelas" => ["10W", "11R", "12W"],
        ],
        [
            "id" => "16",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP003",
            "nama_mata_pelajara" => "English",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Arsy Trilaksono",
            "kelas" => ["8W", "10W", "9Y"],
        ],
        [
            "id" => "17",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP005",
            "nama_mata_pelajara" => "Literature",
            "jumlah_jam" => 7,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Arsy Trilaksono",
            "kelas" => ["9Y", "11R", "10W"],
        ],
        [
            "id" => "18",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP024",
            "nama_mata_pelajara" => "Reading",
            "jumlah_jam" => 7,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Arsy Trilaksono",
            "kelas" => ["7W", "12W", "8W"],
        ],
        [
            "id" => "19",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP025",
            "nama_mata_pelajara" => "Gen Eng",
            "jumlah_jam" => 7,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Arsy Trilaksono",
            "kelas" => ["9W", "8R", "11W"],
        ],
        [
            "id" => "20",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP029",
            "nama_mata_pelajara" => "GP",
            "jumlah_jam" => 7,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Ary Prihatanto",
            "kelas" => ["10W", "10R", "10R"],
        ],
        [
            "id" => "21",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP028",
            "nama_mata_pelajara" => "Geography",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Ary Prihatanto",
            "kelas" => ["7W", "9Y", "12W"],
        ],
        [
            "id" => "22",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP009",
            "nama_mata_pelajara" => "Chem",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Bayu Samodro",
            "kelas" => ["7Y", "8W", "11R"],
        ],
        [
            "id" => "23",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP029",
            "nama_mata_pelajara" => "GP",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Bayu Samodro",
            "kelas" => ["9Y", "10R", "10W"],
        ],
        [
            "id" => "24",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP007",
            "nama_mata_pelajara" => "Math",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Darmita Lumban Gaol",
            "kelas" => ["12W", "8R", "9R"],
        ],
        [
            "id" => "25",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP006",
            "nama_mata_pelajara" => "Literature",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dewi Arlita",
            "kelas" => ["10R", "8R", "10W"],
        ],
        [
            "id" => "26",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP026",
            "nama_mata_pelajara" => "Gen Eng",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dewi Arlita",
            "kelas" => ["9R", "7R", "10W"],
        ],
        [
            "id" => "27",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP005",
            "nama_mata_pelajara" => "English",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dewi Kusumawati",
            "kelas" => ["9Y", "7W", "11R"],
        ],
        [
            "id" => "28",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP026",
            "nama_mata_pelajara" => "Reading",
            "jumlah_jam" => 8,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dewi Kusumawati",
            "kelas" => ["8R", "9Y", "9R"],
        ],
        [
            "id" => "29",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "PE",
            "jumlah_jam" => 8,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dian Ariesta",
            "kelas" => ["11W", "11W", "9Y"],
        ],
        [
            "id" => "30",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP012",
            "nama_mata_pelajara" => "Bio",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dian Yusiana",
            "kelas" => ["12W", "7R", "10W"],
        ],
        [
            "id" => "31",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "Music",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dina Christina",
            "kelas" => ["10W", "8W", "11R"],
        ],
        [
            "id" => "32",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "PE",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Dwi HA Septa Putra",
            "kelas" => ["8W", "9W", "11R"],
        ],
        [
            "id" => "33",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP024",
            "nama_mata_pelajara" => "GP",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Eka Retno Pertiwi",
            "kelas" => ["9Y", "8W", "7R"],
        ],
        [
            "id" => "34",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP027",
            "nama_mata_pelajara" => "Sociology",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Eka Retno Pertiwi",
            "kelas" => ["11R", "10W", "9Y"],
        ],
        [
            "id" => "35",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP009",
            "nama_mata_pelajara" => "Math",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Fatah Rohmani",
            "kelas" => ["11W", "11W", "12W"],
        ],
        [
            "id" => "36",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP011",
            "nama_mata_pelajara" => "Phy",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Fatimah Nopriardy",
            "kelas" => ["11R", "7W", "7Y"],
        ],
        [
            "id" => "37",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP027",
            "nama_mata_pelajara" => "IPA AN",
            "jumlah_jam" => 8,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Fatimah Nopriardy",
            "kelas" => ["8R", "9Y", "8W"],
        ],
        [
            "id" => "38",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP015",
            "nama_mata_pelajara" => "Bio",
            "jumlah_jam" => 8,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Fitryani Achyar",
            "kelas" => ["7Y", "11W", "12W"],
        ],
        [
            "id" => "39",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP009",
            "nama_mata_pelajara" => "Math",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Hero Handy Dinata",
            "kelas" => ["9W", "7W", "10R"],
        ],
        [
            "id" => "40",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP022",
            "nama_mata_pelajara" => "Mat IPA/IPS",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Hero Handy Dinata",
            "kelas" => ["7R", "11R", "9Y"],
        ],
        [
            "id" => "41",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "B.Indo",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Hery Purnama",
            "kelas" => ["11R", "7R", "9R"],
        ],
        [
            "id" => "42",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP027",
            "nama_mata_pelajara" => "PrBL",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Heryanto",
            "kelas" => ["7W", "11W", "7R"],
        ],
        [
            "id" => "43",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP025",
            "nama_mata_pelajara" => "Entre",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Heryanto",
            "kelas" => ["7R", "11W", "12W"],
        ],
        [
            "id" => "44",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP029",
            "nama_mata_pelajara" => "BS",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Heryanto",
            "kelas" => ["11W", "11R", "9Y"],
        ],
        [
            "id" => "45",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "Art",
            "jumlah_jam" => 8,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Ichsan Putrajaya",
            "kelas" => ["7Y", "7W", "11W"],
        ],
        [
            "id" => "46",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP029",
            "nama_mata_pelajara" => "Entre",
            "jumlah_jam" => 8,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Ichsan Putrajaya",
            "kelas" => ["7Y", "12W", "7R"],
        ],
        [
            "id" => "47",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP016",
            "nama_mata_pelajara" => "Chem",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Jennifer Wijaya Lie",
            "kelas" => ["9R", "12W", "8W"],
        ],
        [
            "id" => "48",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP021",
            "nama_mata_pelajara" => "Religion",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Joko Partono",
            "kelas" => ["8W", "7W", "9W"],
        ],
        [
            "id" => "49",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "B.Indo",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Junita Indri",
            "kelas" => ["9Y", "7W", "9R"],
        ],
        [
            "id" => "50",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP029",
            "nama_mata_pelajara" => "PrBL",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Junita Indri",
            "kelas" => ["9Y", "7Y", "7Y"],
        ],
        [
            "id" => "51",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP009",
            "nama_mata_pelajara" => "English",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Marlando Wawolumaya",
            "kelas" => ["7R", "7Y", "9Y"],
        ],
        [
            "id" => "52",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP023",
            "nama_mata_pelajara" => "TS",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Marlando Wawolumaya",
            "kelas" => ["12W", "10R", "9Y"],
        ],
        [
            "id" => "53",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP022",
            "nama_mata_pelajara" => "Religion",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Melkior Sedek",
            "kelas" => ["12W", "8W", "9R"],
        ],
        [
            "id" => "54",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP022",
            "nama_mata_pelajara" => "Religion",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Millata Hanifah",
            "kelas" => ["10W", "9R", "8W"],
        ],
        [
            "id" => "55",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP016",
            "nama_mata_pelajara" => "Phy",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Muhamad Ihsan Fauzi",
            "kelas" => ["8W", "10W", "7W"],
        ],
        [
            "id" => "56",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "B.Indo",
            "jumlah_jam" => 4,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Nita Ernita",
            "kelas" => ["9R", "10W", "8R"],
        ],
        [
            "id" => "57",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "PrBL",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Nita Ernita",
            "kelas" => ["11R", "11R", "9Y"],
        ],
        [
            "id" => "58",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP010",
            "nama_mata_pelajara" => "English",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Nur Abdina Jamila",
            "kelas" => ["8R", "9W", "11R"],
        ],
        [
            "id" => "59",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP012",
            "nama_mata_pelajara" => "Literature",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Nur Abdina Jamila",
            "kelas" => ["9Y", "9R", "7R"],
        ],
        [
            "id" => "60",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP024",
            "nama_mata_pelajara" => "Religion",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Nyaman",
            "kelas" => ["10R", "7W", "12W"],
        ],
        [
            "id" => "61",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP022",
            "nama_mata_pelajara" => "Art",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Philosophia",
            "kelas" => ["10W", "7R", "10R"],
        ],
        [
            "id" => "62",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "PrBL",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Philosophia",
            "kelas" => ["8W", "7R", "12W"],
        ],
        [
            "id" => "63",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP029",
            "nama_mata_pelajara" => "Entre",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Philosophia",
            "kelas" => ["12W", "10W", "11W"],
        ],
        [
            "id" => "64",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP024",
            "nama_mata_pelajara" => "DT",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Robert Thompson",
            "kelas" => ["9W", "9Y", "11R"],
        ],
        [
            "id" => "65",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "SS",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Rosininta Mega Inneke",
            "kelas" => ["10R", "9R", "8W"],
        ],
        [
            "id" => "66",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "PrBL",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Rosininta Mega Inneke",
            "kelas" => ["10W", "8W", "9R"],
        ],
        [
            "id" => "67",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP025",
            "nama_mata_pelajara" => "Religion",
            "jumlah_jam" => 3,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Samuel D. Hasiholan",
            "kelas" => ["9R", "10R", "9R"],
        ],
        [
            "id" => "68",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP024",
            "nama_mata_pelajara" => "GP",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Sebastianus Sambi",
            "kelas" => ["8R", "11R", "12W"],
        ],
        [
            "id" => "69",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP027",
            "nama_mata_pelajara" => "Sociology",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Sebastianus Sambi",
            "kelas" => ["7Y", "8W", "8W"],
        ],
        [
            "id" => "70",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "Bio",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Sigit Kurniawan",
            "kelas" => ["7Y", "11R", "11R"],
        ],
        [
            "id" => "71",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP019",
            "nama_mata_pelajara" => "IPA AN",
            "jumlah_jam" => 1,
            "max_jam" => "1",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Sigit Kurniawan",
            "kelas" => ["9Y", "8R", "10W"],
        ],
        [
            "id" => "72",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP024",
            "nama_mata_pelajara" => "GP",
            "jumlah_jam" => 1,
            "max_jam" => "1",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Steve Edpin",
            "kelas" => ["9R", "10R", "11W"],
        ],
        [
            "id" => "73",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP029",
            "nama_mata_pelajara" => "BS",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Steve Edpin",
            "kelas" => ["9Y", "7R", "7W"],
        ],
        [
            "id" => "74",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP026",
            "nama_mata_pelajara" => "Econ",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Tengku Andyka",
            "kelas" => ["10W", "9R", "9R"],
        ],
        [
            "id" => "75",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP028",
            "nama_mata_pelajara" => "Religion",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Wendy Pangestu",
            "kelas" => ["8W", "9R", "11R"],
        ],
        [
            "id" => "76",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP022",
            "nama_mata_pelajara" => "Mat IPA/IPS",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Woro Retno Kris Sejati",
            "kelas" => ["9W", "10R", "10W"],
        ],
        [
            "id" => "77",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP016",
            "nama_mata_pelajara" => "English",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Yanty Oktalia",
            "kelas" => ["10R", "8W", "8R"],
        ],
        [
            "id" => "78",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP017",
            "nama_mata_pelajara" => "Literature",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Yanty Oktalia",
            "kelas" => ["10W", "9R", "10R"],
        ],
        [
            "id" => "79",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP020",
            "nama_mata_pelajara" => "Reading",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Yanty Oktalia",
            "kelas" => ["9W", "10R", "11W"],
        ],
        [
            "id" => "80",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP018",
            "nama_mata_pelajara" => "Chem",
            "jumlah_jam" => 6,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["9W", "12W", "9W"],
        ],
        [
            "id" => "81",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP019",
            "nama_mata_pelajara" => "IPA AN",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "0",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["10R", "11W", "12W"],
        ],
        [
            "id" => "82",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9999",
            "nama_mata_pelajara" => "Chem/Geo/AM",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["12W"],
        ],
        [
            "id" => "83",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9998",
            "nama_mata_pelajara" => "Econ/Bio Darwin/Socio Marx",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["9W", "9R", "9Y"],
        ],
        [
            "id" => "84",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9997",
            "nama_mata_pelajara" => "Art/DT/BS/CS",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["9W", "9R", "9Y"],
        ],
        [
            "id" => "85",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9996",
            "nama_mata_pelajara" => "Socio Parsons/Phy/Lit/Bio Mendel",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["9W", "9R", "9Y"],
        ],
        [
            "id" => "86",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9995",
            "nama_mata_pelajara" => "Lit/AM/Bio",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["10W", "10R"],
        ],
        [
            "id" => "87",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9994",
            "nama_mata_pelajara" => "Phy Newton/Econ/Chem Lewis",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["10W", "10R"],
        ],
        [
            "id" => "88",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9993",
            "nama_mata_pelajara" => "Chem/Geo/AM",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["11R", "11W"],
        ],
        [
            "id" => "89",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9992",
            "nama_mata_pelajara" => "Mat IPA/IPS",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["11R", "11W"],
        ],
        [
            "id" => "90",
            "preferredDay" => [],
            "preferredTime" => [],
            "mata_pelajaran_ref" => "MP9991",
            "nama_mata_pelajara" => "Chem/Socio/Eng-A",
            "jumlah_jam" => 2,
            "max_jam" => "2",
            "semester" => "1",
            "is_penjuruan" => "1",
            "nama_guru" => "Yasmine Nur Fitria",
            "kelas" => ["11R", "11W"],
        ],
    ];

    public $data_jam = [
        ['MP', '7:20','7:30'],
        ['1', '7:30','8:10'],
        ['2', '8:10','8:50'],
        ['3', '8:50','9:30'],
        ['4', '9:30','10:10'],
        ['RECESS', '10:10','10:25'],
        ['5', '10:25','11:05'],
        ['6', '11:05','11:45'],
        ['7', '11:45','12:25'],
        ['LUNCH', '12:25','12:55'],
        ['8', '12:55','13:35'],
        ['9', '13:35','14:15'],
        ['10', '14:15','14:55'],
        ['HR', '14:55','15:00'],
    ];

    static function removeStringInArray($arr) : array {
        $result = [];
        
        foreach ($arr as $value) {
            if (is_string($value) !== true) {
                $result[] = $value;
            }
        }

        return $result;
    }

    static function removeDuplicate($rangeArray) : array {
        $result = [];
        $tmpRangeArrayId = [];
        
        foreach ($rangeArray as $value) {
            if (count($tmpRangeArrayId) > 0) {
                $indexIfAny = null;
                foreach ($tmpRangeArrayId as $valueInner) {
                    if ($value['id'] !== $valueInner) {
                        $indexIfAny = 1;
                    }
                }

                if (!is_null($indexIfAny)) {
                    $result[] = $value;
                    $tmpRangeArrayId[] = $value['id'];
                }
            } else {
                $result[] = $value;
                $tmpRangeArrayId[] = $value['id'];
            }
        }
        
        return $result;
    }
    
    static function getRandomId($rangeArray, $checkArray, $currenPosition, $position, $day) {
        // $removeTarget = ['BELAJAR', 'MP', 'RECESS', 'LUNCH', 'DISMISSAL', 'PRAY'];
        $verticalNumbers = [];
        $horizontalNumbers = $checkArray[$currenPosition];
        $rangeArrayWithCriteria = [];
        $rangeArrayWithoutCriteria = [];
        
        for ($i = 0; $i < count($checkArray); $i++) {
            $verticalNumbers[] = $checkArray[$i][$position]; 
        }

        foreach ($rangeArray as $value) {
            if (count($value['preferredDay']) > 0) {
                foreach ($value['preferredDay'] as $valueDay) {
                    if ($valueDay == $day) {
                        $rangeArrayWithCriteria[] = $value;
                    }
                }
            } else {
                $rangeArrayWithoutCriteria[] = $value;
            }

            if (count($value['preferredTime']) > 0) {
                foreach ($value['preferredTime'] as $valueTime) {
                    if ($valueTime == $currenPosition) {
                        $rangeArrayWithCriteria[] = $value;
                    }
                }
            } else {
                $rangeArrayWithoutCriteria[] = $value;
            }
        }
        $dataWithCriteria = self::removeDuplicate($rangeArrayWithCriteria);
        $dataWithoutCriteria = self::removeDuplicate($rangeArrayWithoutCriteria);
        $horizontalNumbers = self::removeDuplicate(self::removeStringInArray($horizontalNumbers));
        $verticalNumbers = self::removeDuplicate(self::removeStringInArray($verticalNumbers));
        $dataVerticalHorizontalNumbersMerge = self::removeDuplicate(array_merge($horizontalNumbers, $verticalNumbers));

        foreach ($dataVerticalHorizontalNumbersMerge as  $value) {
            foreach ($dataWithCriteria as $key => $valueInner) {
                if ($valueInner['id'] == $value['id']) {
                    array_splice($dataWithCriteria, $key, 1);
                }

                if ($valueInner['mata_pelajaran_ref'] == $value['mata_pelajaran_ref']) {
                    array_splice($dataWithCriteria, $key, 1);
                }

                // if ($valueInner['id_guru'] == $value['id_guru']) {
                //     array_splice($dataWithCriteria, $key, 1);
                // }
            }

            foreach ($dataWithoutCriteria as $key => $valueInner) {
                if ($valueInner['id'] == $value['id']) {
                    array_splice($dataWithoutCriteria, $key, 1);
                }

                if ($valueInner['mata_pelajaran_ref'] == $value['mata_pelajaran_ref']) {
                    array_splice($dataWithoutCriteria, $key, 1);
                }

                // if ($valueInner['id_guru'] == $value['id_guru']) {
                //     array_splice($dataWithoutCriteria, $key, 1);
                // }
            }
        }

        $randomKey = false;
        $randomNumber = false;

        if (count($dataWithCriteria) > 0) {
            $randomKey = array_rand($dataWithCriteria);
            $randomNumber = $dataWithCriteria[$randomKey];
        } else if (count($dataWithoutCriteria) > 0) {
            $randomKey = array_rand($dataWithoutCriteria);
            $randomNumber = $dataWithoutCriteria[$randomKey];
        }

        return $randomNumber;
    }
}
